### ISSUE TITLE
Bug: when changing the isOpen prop to false.

### ISSUE THREAD

**Issue by VadymBezsmertnyi** [Memcrab/react-pure-modal#84]
After changing the isOpen prop to false, the _body-modal-fix_ style class is not being removed from the body tag DOM.

**Comment by Xaypanya** [comment]
I have also encountered this error. Have you found any temporary solutions?

**Comment by VadymBezsmertnyi** [comment]
> I have also encountered this issue. Have you found any temporary solutions?

Yes, sure. Example:
```
function onClose(){
setIsOpenModal(false);
document.body.classList.remove('body-modal-fix');
}
```
